 POST https://api.openai.com/v1/completions
 Content-Type: application/json
 Authorization: Bearer "YOUR API KEY"

 {
   "model": "text-davinci-003",
   "prompt": "What is the capital of INDIA?",
   "max_tokens": 5
 }


// -----------------------------------------------------------------------------------------------------------------
// OR YOU CAN USE:

// MAKE SURE YOU CHANGE YOUR_API_KEY IN POST
// HOVER ON POST AND CLICK SEND REQUEST HENCE IT WILL HIT THE API AND WILL REFLECT THE OUTPUT FROM HTTP REQUEST

POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=YOUR_API_KEY
Content-Type: application/json

{
  "contents": [
    {
      "parts": [
        {
          "text": "what is the capital of India?"
        }
      ]
    }
  ]
}
